apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook-applicationset
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/vedantsharmascaler/applicationsets-repo
        revision: HEAD
        directories:
          - path: dev
          - path: staging
          - path: production
  template:
    metadata:
      name: '{{path.basename}}-guestbook'
    spec:
      project: default
      source:
        repoURL: https://github.com/vedantsharmascaler/applicationsets-repo
        path: '{{path}}'
        targetRevision: HEAD
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
